In [11]:
import pandas as pd
import holoviews as hv
import hvplot.pandas
import datetime as dt
import numpy as np
        ### imported numpys to get a better looking heatmap 
%matplotlib inline

In [12]:
df_btc_moon = pd.read_csv(
                                "bitcoin moon.csv",
                                index_col="date",
                                parse_dates=True,
                                infer_datetime_format=True)

df_btc_moon.head(73)

In [13]:
df_btc_moon.head(73)

,new price open,new price close,t+1 new,t+2 new,t+3 new,t+4 new,t+5 new,t+6 new,full price open,full price close,...,%Ft+2,Unnamed: 36,%F t+3,Unnamed: 38,%ft+4,Unnamed: 40,%ft+5,Unnamed: 42,%ft+6,Unnamed: 44
date,,,,,,,,,,,,,,,,,,,,,
1/9/16 -1/23/16,453.38,447.61,447.99,448.43,435.69,432.37,430.31,364.33,382.43,387.5,...,1.09%,1.62%,1.20%,-3.98%,1.93%,106.50%,-1.86%,81.15%,-2.07%,24.86%
2/8/16-2/22/16,376.76,373.33,376.03,381.65,379.65,384.26,391.86,407.23,438.99,437.75,...,-2.92%,right 38,-3.02%,right 41,-1.28%,right 43,-1.19%,right 35,-0.97%,right 34
3/8/16-3/23/16,414.56,413.97,414.86,417.13,421.69,411.62,414.07,416.44,418.16,418.04,...,-0.21%,0,-0.02%,6.99%,2.09%,21.94%,1.48%,39.64%,-0.36%,35.72%
4/7/16-4/22/16,423.62,422.74,420.35,419.41,421.56,422.48,425.19,423.73,449.69,445.74,...,2.87%,NaN,3.52%,NaN,4.57%,NaN,-0.24%,NaN,0.73%,NaN
5/6/16-5/21/16,447.94,459.6,458.54,458.55,460.48,450.89,452.73,454.77,442.97,443.19,...,0.22%,NaN,0.63%,NaN,1.45%,NaN,2.30%,NaN,6.83%,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7/9/21-7/23/21,"32,861.67","33,798.01","33,520.52","34,240.19","33,155.85","32,702.03","32,822.35","31,780.73","32,305.96","33,581.55",...,5.27%,NaN,11.18%,NaN,17.35%,NaN,19.10%,NaN,19.14%,NaN
8/8/21-8/22/21,"44,574.44","43,798.12","46,365.40","45,585.03","45,593.64","44,428.29","47,793.32","47,096.95","48,869.11","49,321.65",...,-3.28%,NaN,-0.73%,NaN,-4.82%,NaN,-0.53%,NaN,-0.85%,NaN
9/6/21-9/20/21,"51,769.00","52,633.54","46,811.13","46,091.39","46,391.42","44,883.91","45,201.46","46,063.27","47,261.41","42,843.80",...,1.71%,NaN,4.79%,NaN,-0.01%,NaN,-0.30%,NaN,0.85%,NaN
10/6/21-10/20/21,"51,486.66","55,361.45","53,805.98","53,967.85","54,968.22","54,771.58","57,484.79","56,041.06","64,284.59","65,992.84",...,-8.03%,NaN,-6.97%,NaN,-7.67%,NaN,-4.47%,NaN,-8.53%,NaN
11/4/21-11/19/21,"62,941.80","61,452.23","61,125.68","61,527.48","63,326.99","67,566.83","66,971.83","64,995.23","56,896.13","58,119.58",...,1.05%,NaN,-3.15%,NaN,-0.95%,NaN,-3.16%,NaN,-1.45%,NaN